//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DB_TiquetesEntidades : DbContext
    {
        public DB_TiquetesEntidades()
            : base("name=DB_TiquetesEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Aplicacion> T_Aplicacion { get; set; }
        public DbSet<T_Cliente> T_Cliente { get; set; }
        public DbSet<T_Estado_Tiquetes> T_Estado_Tiquetes { get; set; }
        public DbSet<T_Severidades> T_Severidades { get; set; }
        public DbSet<T_Tiquete> T_Tiquete { get; set; }
        public DbSet<T_Usuarios> T_Usuarios { get; set; }
    
        public virtual ObjectResult<LOGIN_Result> LOGIN(string iDUSER, string pASSW)
        {
            var iDUSERParameter = iDUSER != null ?
                new ObjectParameter("IDUSER", iDUSER) :
                new ObjectParameter("IDUSER", typeof(string));
    
            var pASSWParameter = pASSW != null ?
                new ObjectParameter("PASSW", pASSW) :
                new ObjectParameter("PASSW", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOGIN_Result>("LOGIN", iDUSERParameter, pASSWParameter);
        }
    }
}
