//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Aplicacion
    {
        public int Id_Aplicacion { get; set; }
        public string Nombre_Aplicacion { get; set; }
        public string Descripcion_Aplicacion { get; set; }
    }
}
