//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Cliente
    {
        public int Id_Cliente { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Telefono_Cliente { get; set; }
        public string Correo_Cliente { get; set; }
        public string Region_Cliente { get; set; }
        public string Pais_Cliente { get; set; }
        public string Focal_Cliente { get; set; }
        public string Tipo_Servidor { get; set; }
        public string Nombre_Servidor { get; set; }
        public string Ip_Servidor { get; set; }
        public string Estado_Servidor { get; set; }
    }
}
