//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Tiquete
    {
        public int Id_Tiquete { get; set; }
        public int Id_Supervisor { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Nombre_Aplicacion { get; set; }
        public string Numero_Tiquete { get; set; }
        public int Severidad_Tiquete { get; set; }
        public string Estado_Tiquete { get; set; }
        public string Comentarios_Tiquete { get; set; }
        public Nullable<System.DateTime> HorayFecha_Apertura { get; set; }
        public Nullable<System.DateTime> HorayFecha_Cierre { get; set; }
    }
}
