//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Usuarios
    {
        public int Id_Usuario { get; set; }
        public string Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Contrasena_Usuario { get; set; }
        public string Estado_Usuario { get; set; }
        public string Tipo_Usuario { get; set; }
    }
}
